import { getSupportedRegionCodes } from "../../../lib/regionSupport";

export const OWNER_PAGE_KEY = "kinly_fit_check_owner";
export const CANDIDATE_JOIN_PAGE_KEY = "kinly_fit_check_candidate_join";
export const CANDIDATE_RESULT_PAGE_KEY = "kinly_fit_check_candidate_result";

export const fitCheckCopy = {
  owner: {
    eyebrow: "Free flatmate screening tool",
    title: "Know what to ask before the interview.",
    subtitle: "Answer 4 quick questions to generate your applicant link.",
    valueTitle: "What you'll get",
    valuePoint1: "A short applicant link you can send straight away",
    valuePoint2: "Targeted interview questions based on likely friction points",
    valuePoint3: "A clearer sense of what matters in your home before anyone moves in",
    valueOpen: "Why this helps",
    valueClose: "Hide details",
    statText: "9 in 10 young flat sharers say they've lived with a housemate horror",
    statSource: "Barclays, 2025",
    statUrl: "https://home.barclays/news/press-releases/2025/10/nine-in-10-young-flat-sharers-say-they-ve-lived-with-a--housemat/",
    locationTitle: "Where are you at?",
    locationBody: "One last step before we generate your applicant link.",
    countryLabel: "Country",
    countryHint: "Choose the country.",
    cityLabel: "City",
    cityHint: "Pick the closest city from the list.",
    cityPlaceholder: "Search for your city",
    priorityCitiesTitle: "Popular cities",
    otherCitiesTitle: "Other cities",
    cityEmpty: "No matching cities yet for that country.",
    missingLocation: "Choose your country and city before generating the link.",
    continueToLocation: "Add location",
    questionsTitle: "Use these interview questions",
    questionsSubtitle: "Preview the questions most likely to surface deal-breakers.",
    questionsHelper: "Use this as a live checklist once you start interviewing.",
    questionToggleUnchecked: "Mark question as asked",
    questionToggleChecked: "Question asked",
    comparisonPreviewTitle: "See how comparisons work",
    comparisonPreviewBody: "Preview the kind of signals Kinly shows once real applicants respond.",
    comparisonPreviewOpen: "Show example",
    comparisonPreviewClose: "Hide example",
    comparisonPreviewHint: "Example only — real comparisons appear after applicants respond.",
    comparisonAligned: "Aligned",
    comparisonAskMore: "Worth asking about",
    comparisonMismatch: "Potential mismatch",
    questionsPreviewOpen: "Preview interview questions",
    questionsPreviewClose: "Hide interview questions",
    shareTitle: "Share this applicant link",
    shareHelp: "Applicants answer anonymously from this link.",
    copyLink: "Copy link",
    copied: "Copied",
    signInTitle: "Track real applicants in Kinly",
    signInBody:
      "Sign in to see applicant comparisons and manage replies in one place.",
    signInGoogle: "Continue with Google",
    signInApple: "Continue with Apple",
    successTitle: "Your fit check is ready!",
    successBody: "Share the link with shortlisted applicants, then use Kinly to review responses.",
    submit: "Create fit check link",
    update: "Update fit check",
    missingAnswers: "Answer all four questions to continue.",
    next: "Next",
    back: "Back",
    progressLabel: "Step",
  },
  candidate: {
    title: "Share how you live day to day.",
    subtitle:
      "This is a quick, anonymous vibe check before the viewing or interview. Your answers help the household know what to ask next.",
    displayNameLabel: "First name or nickname",
    displayNameHint: "This is how the household will recognize your submission.",
    displayNamePlaceholder: "e.g. Alex",
    locationTitle: "Add your location",
    locationBody: "Choose your country and city before you send your answers.",
    countryLabel: "Country",
    countryHint: "You can change the pre-selected country if it looks wrong.",
    cityLabel: "City",
    cityHint: "Choose a city from the list for your selected country.",
    cityPlaceholder: "Search for your city",
    priorityCitiesTitle: "Priority cities",
    otherCitiesTitle: "Other cities",
    cityEmpty: "No matching cities for that country yet.",
    continueToLocation: "Continue to location",
    submit: "Send my answers",
    invalidLink: "This fit check link is unavailable.",
    invalidHelp: "If the household still wants your answers, ask them for a fresh link.",
    missingLocation: "Choose your country and city before continuing.",
    next: "Next",
    back: "Back",
    progressLabel: "Step",
  },
  result: {
    title: "Your flatmate fit check is complete.",
    subtitle:
      "This page reflects only your own answers. It does not compare you with the household or other applicants.",
    appTitle: "Keep this in Kinly",
    appBody:
      "Download the app if you want to keep your living-style profile handy for future homes and shared-living conversations.",
    learnMore: "Learn more about Kinly",
    unavailable: "This personalized result is not available on this device.",
    locationPrefix: "Location:",
  },
  app: {
    iosLabel: "Download on the App Store",
    androidLabel: "Get it on Google Play",
    fallbackTitle: "Availability",
    fallbackBody: `Kinly is currently available in ${getSupportedRegionCodes().join(", ")}.`,
  },
};
